In [458]:
import pandas as pd

In [459]:
df = pd.read_csv(r"C:\Users\hp pavilion\Downloads\world_population.csv") # we can use index_col = 0 for set index
# or we can use for set index  df.set_index('Country', inplace = True) the use of inplace is to set the index in the same dataframe

df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [460]:
df2 = df.set_index('Continent').sort_values(by= 'Capital') # we can use sort_value(by='Rank', ascending= True) for sort the data
df2
# df.sort_values(by = ['Continent', 'Capital'], ascending = [True, True]) # we can use this for sort the data by multiple columns

,Rank,CCA3,Country,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,,,,
Asia,97,ARE,United Arab Emirates,Abu Dhabi,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
Africa,6,NGA,Nigeria,Abuja,218541212.0,208327405.0,183995785.0,160952853.0,122851984.0,95214257.0,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
Africa,47,GHA,Ghana,Accra,33475870.0,32180401.0,28870939.0,25574719.0,19665502.0,15446982.0,11865246.0,8861895.0,238533.0,140.3406,1.0196,0.42
Africa,12,ETH,Ethiopia,Addis Ababa,123379924.0,117190911.0,102471895.0,89237791.0,67031867.0,47878073.0,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
Africa,34,DZA,Algeria,Algiers,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Africa,52,CIV,Ivory Coast,Yamoussoukro,28160542.0,26811790.0,23596741.0,21120042.0,16799670.0,11910540.0,8303809.0,5477086.0,322463.0,NaN,NaN,0.35
Africa,53,CMR,Cameroon,Yaounde,27914536.0,26491087.0,23012646.0,19878036.0,15091594.0,11430520.0,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
Oceania,225,NRU,Nauru,Yaren,12668.0,12315.0,11185.0,10241.0,10377.0,9598.0,7635.0,6663.0,21.0,603.2381,1.0125,0.00
Asia,140,ARM,Armenia,Yerevan,2780469.0,2805608.0,2878595.0,2946293.0,3168523.0,3556539.0,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03
Europe,130,HRV,Croatia,Zagreb,4030358.0,4096868.0,4254815.0,4368682.0,4548434.0,4873707.0,4680144.0,4492638.0,56594.0,71.2153,0.9927,0.05

In [461]:
df2.iloc[4]

Rank                                   34
CCA3                                  DZA
Country                           Algeria
Capital                           Algiers
2022 Population                44903225.0
2020 Population                43451666.0
2015 Population                39543154.0
2010 Population                35856344.0
2000 Population                30774621.0
1990 Population                25518074.0
1980 Population                18739378.0
1970 Population                13795915.0
Area (km²)                      2381741.0
Density (per km²)                 18.8531
Growth Rate                        1.0164
World Population Percentage          0.56
Name: Africa, dtype: object

In [462]:
df3 = df2.loc['Asia']
df3

,Rank,CCA3,Country,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,,,,,
Asia,97,ARE,United Arab Emirates,Abu Dhabi,9.441129e+06,9.287289e+06,8.916899e+06,8.481771e+06,3.275333e+06,1.900151e+06,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
Asia,83,JOR,Jordan,Amman,1.128587e+07,1.092872e+07,9.494246e+06,6.931258e+06,5.056174e+06,3.480587e+06,2216903.0,1557374.0,89342.0,126.3221,1.0123,0.14
Asia,18,TUR,Turkey,Ankara,8.534124e+07,8.413543e+07,7.964618e+07,7.319534e+07,6.411355e+07,5.432414e+07,44089069.0,35540990.0,783562.0,108.9145,1.0067,1.07
Asia,111,TKM,Turkmenistan,Ashgabat,6.430770e+06,6.250438e+06,5.766431e+06,5.267970e+06,4.569132e+06,3.720278e+06,2862903.0,2201432.0,488100.0,13.1751,1.0140,0.08
Asia,35,IRQ,Iraq,Baghdad,4.449612e+07,4.255698e+07,3.775781e+07,3.126488e+07,2.462886e+07,1.765838e+07,13653369.0,9811347.0,438317.0,101.5158,1.0221,0.56
Asia,91,AZE,Azerbaijan,Baku,1.035807e+07,NaN,9.863480e+06,9.237202e+06,8.190337e+06,7.427836e+06,6383060.0,5425317.0,86600.0,119.6082,1.0044,0.13
Asia,175,BRN,Brunei,Bandar Seri Begawan,4.490020e+05,4.417250e+05,4.214370e+05,3.960530e+05,3.339260e+05,2.619280e+05,187921.0,133343.0,5765.0,77.8841,1.0081,0.01
Asia,20,THA,Thailand,Bangkok,7.169703e+07,7.147566e+07,7.029440e+07,6.827049e+07,6.306660e+07,5.522841e+07,45737753.0,NaN,513120.0,139.7276,1.0013,0.90
Asia,1,CHN,China,Beijing,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
Asia,119,LBN,Lebanon,Beirut,5.489739e+06,5.662923e+06,6.398940e+06,4.995800e+06,4.320642e+06,3.593700e+06,2963702.0,2381791.0,10452.0,525.2334,0.9816,0.07
Asia,110,KGZ,Kyrgyzstan,Bishkek,6.630623e+06,6.424874e+06,5.914980e+06,5.483774e+06,4.935182e+06,4.394734e+06,3691209.0,3016384.0,199951.0,33.1612,1.0158,0.08
Asia,61,LKA,Sri Lanka,Colombo,2.183214e+07,2.171508e+07,2.133670e+07,2.066856e+07,1.877637e+07,1.720409e+07,14943645.0,12388769.0,65610.0,332.7563,1.0027,0.27
Asia,167,MAC,Macau,Concelho de Macau,6.951680e+05,6.762830e+05,6.152390e+05,5.572970e+05,4.318960e+05,3.502270e+05,245332.0,247284.0,30.0,23172.2667,1.0125,0.01
Asia,60,SYR,Syria,Damascus,2.212525e+07,2.077260e+07,1.920518e+07,2.233756e+07,1.630765e+07,1.240900e+07,8898954.0,6319199.0,185180.0,119.4797,1.0376,0.28
Asia,8,BGD,Bangladesh,Dhaka,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
Asia,155,TLS,Timor-Leste,Dili,NaN,1.299995e+06,1.205813e+06,1.088486e+06,NaN,7.581060e+05,642224.0,554021.0,14874.0,90.1772,1.0154,0.02
Asia,143,QAT,Qatar,Doha,2.695122e+06,2.760385e+06,2.414573e+06,1.713504e+06,6.459370e+05,4.416750e+05,277450.0,118007.0,11586.0,232.6189,1.0026,0.03
Asia,95,TJK,Tajikistan,Dushanbe,9.952787e+06,9.543207e+06,8.524063e+06,7.621779e+06,6.272998e+06,5.417860e+06,4045965.0,2993019.0,143100.0,69.5513,1.0208,0.12
Asia,16,VNM,Vietnam,Hanoi,9.818686e+07,9.664868e+07,9.219140e+07,8.741101e+07,7.900114e+07,6.691261e+07,52968270.0,41928849.0,331212.0,296.4472,1.0074,1.23
Asia,104,HKG,Hong Kong,Hong Kong,7.488865e+06,7.500958e+06,7.399838e+06,7.132438e+06,6.731195e+06,5.838574e+06,4978544.0,3955072.0,1104.0,6783.3922,0.9992,0.09
Asia,5,PAK,Pakistan,Islamabad,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
Asia,4,IDN,Indonesia,Jakarta,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
Asia,98,ISR,Israel,Jerusalem,9.038309e+06,8.757489e+06,8.007778e+06,7.328445e+06,6.116958e+06,4.803254e+06,3744608.0,2907307.0,20770.0,435.1617,1.0155,0.11
Asia,36,AFG,Afghanistan,Kabul,4.112877e+07,3.897223e+07,3.375350e+07,2.818967e+07,1.954298e+07,1.069480e+07,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Asia,49,NPL,Nepal,Kathmandu,3.054758e+07,2.934863e+07,2.761032e+07,2.716157e+07,2.455950e+07,1.961653e+07,15600442.0,12501285.0,147181.0,207.5511,1.0171,0.38
Asia,45,MYS,Malaysia,Kuala Lumpur,3.393822e+07,3.319999e+07,3.106883e+07,NaN,NaN,1.751705e+07,13215707.0,10306508.0,330803.0,102.5934,1.0109,0.43
Asia,129,KWT,Kuwait,Kuwait City,4.268873e+06,4.360444e+06,3.908743e+06,2.943356e+06,1.934901e+06,1.674938e+06,1493870.0,802786.0,17818.0,239.5821,1.0044,0.05
Asia,174,MDV,Maldives,Malé,5.237870e+05,5.144380e+05,4.355820e+05,NaN,NaN,2.249570e+05,164887.0,123243.0,300.0,1745.9567,1.0045,0.01
Asia,154,BHR,Bahrain,Manama,1.472233e+06,1.477469e+06,1.362142e+06,1.213645e+06,7.114420e+05,5.174180e+05,362595.0,222555.0,765.0,1924.4876,1.0061,0.02
Asia,13,PHL,Philippines,Manila,1.155590e+08,1.121910e+08,1.030314e+08,9.463670e+07,7.795822e+07,6.155890e+07,48419546.0,37435586.0,342353.0,337.5434,1.0147,1.45
Asia,127,OMN,Oman,Muscat,4.576298e+06,4.543399e+06,4.191776e+06,2.881914e+06,2.344253e+06,1.804524e+06,1017462.0,670693.0,309500.0,14.7861,1.0123,0.06
Asia,26,MMR,Myanmar,Nay Pyi Taw,5.417931e+07,5.342320e+07,5.148395e+07,4.939099e+07,4.553833e+07,4.009955e+07,33465781.0,27284112.0,676578.0,80.0784,1.0071,0.68
Asia,2,IND,India,New Delhi,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
Asia,66,KAZ,Kazakhstan,Nursultan,1.939800e+07,1.897924e+07,1.783591e+07,1.662784e+07,1.523625e+07,1.686656e+07,14172710.0,12265305.0,2724900.0,7.1188,1.0105,0.24
Asia,73,KHM,Cambodia,Phnom Penh,1.676784e+07,1.639686e+07,1.541752e+07,1.436353e+07,1.211884e+07,8.910808e+06,6198959.0,6708525.0,181035.0,92.6221,1.0108,0.21
Asia,56,PRK,North Korea,Pyongyang,2.606942e+07,2.586747e+07,2.525802e+07,2.468644e+07,2.336706e+07,2.079952e+07,17973650.0,14996879.0,120538.0,216.2755,1.0038,0.33
Asia,122,PSE,Palestine,Ramallah,5.250072e+06,5.019401e+06,4.484614e+06,3.992278e+06,3.139954e+06,2.124609e+06,1453620.0,1118241.0,6220.0,844.0630,1.0227,0.07
Asia,41,SAU,Saudi Arabia,Riyadh,3.640882e+07,3.599711e+07,3.274985e+07,2.941193e+07,2.154739e+07,1.600476e+07,10171710.0,6106191.0,2149690.0,16.9368,1.0128,0.46
Asia,46,YEM,Yemen,Sanaa,3.369661e+07,3.228405e+07,2.851654e+07,2.474395e+07,1.862870e+07,1.337512e+07,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Asia,29,KOR,South Korea,Seoul,5.181581e+07,5.184469e+07,5.099440e+07,4.881304e+07,4.678859e+07,4.412004e+07,38170501.0,32601143.0,100210.0,517.0722,0.9997,0.65
Asia,113,SGP,Singapore,Singapore,5.975689e+06,5.909869e+06,5.650018e+06,5.163590e+06,4.053602e+06,3.022209e+06,2400729.0,2061831.0,710.0,8416.4634,1.0058,0.07
Asia,57,TWN,Taiwan,Taipei,2.389339e+07,2.382146e+07,2.351214e+07,2.308308e+07,2.219473e+07,2.058617e+07,18100281.0,14957870.0,36193.0,660.1662,1.0014,0.30
Asia,43,UZB,Uzbekistan,Tashkent,3.462765e+07,3.352666e+07,3.094942e+07,2.861423e+07,2.492555e+07,2.057910e+07,15947129.0,12011361.0,447400.0,77.3975,1.0160,0.43
Asia,131,GEO,Georgia,Tbilisi,3.744385e+06,3.765912e+06,3.771132e+06,NaN,NaN,NaN,NaN,NaN,69700.0,53.7214,0.9964,0.05
Asia,17,IRN,Iran,Tehran,8.855057e+07,8.729019e+07,8.179084e+07,7.537386e+07,6.554438e+07,5.579363e+07,38520664.0,28449705.0,1648195.0,53.7258,1.0071,1.11
Asia,165,BTN,Bhutan,Thimphu,7.824550e+05,7.725060e+05,7.432740e+05,7.055160e+05,5.872070e+05,5.584420e+05,415257.0,298894.0,38394.0,20.3796,1.0064,0.01
Asia,11,JPN,Japan,Tokyo,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.9947,1.55
Asia,134,MNG,Mongolia,Ulaanbaatar,3.398366e+06,3.294335e+06,2.964749e+06,2.702520e+06,2.450979e+06,2.161433e+06,1697780.0,1293880.0,1564110.0,2.1727,1.0151,0.04
Asia,103,LAO,Laos,Vientiane,7.529475e+06,7.319399e+06,6.787419e+06,6.323418e+06,5.430853e+06,4.314443e+06,3297519.0,2675283.0,236800.0,31.7968,1.0141,0.09
Asia,140,ARM,Armenia,Yerevan,2.780469e+06,2.805608e+06,2.878595e+06,2.946293e+06,3.168523e+06,3.556539e+06,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03

In [463]:
df3.iloc[4]

Rank                                   35
CCA3                                  IRQ
Country                              Iraq
Capital                           Baghdad
2022 Population                44496122.0
2020 Population                42556984.0
2015 Population                37757813.0
2010 Population                31264875.0
2000 Population                24628858.0
1990 Population                17658381.0
1980 Population                13653369.0
1970 Population                 9811347.0
Area (km²)                       438317.0
Density (per km²)                101.5158
Growth Rate                        1.0221
World Population Percentage          0.56
Name: Asia, dtype: object

In [470]:

df4 = df.set_index(['Continent', 'Country']).sort_index( ascending = (True, False)) # we can use this for sort the data by multiple columns
df4

                              Rank CCA3       Capital  2022 Population  \
Continent     Country
Africa        Zimbabwe          74  ZWE        Harare       16320537.0
              Zambia            63  ZMB        Lusaka       20017675.0
              Western Sahara   172  ESH      El Aaiún         575986.0
              Uganda            31  UGA       Kampala       47249585.0
              Tunisia           79  TUN         Tunis       12356117.0
...                            ...  ...           ...              ...
South America Colombia          28  COL        Bogota       51874024.0
              Chile             65  CHL      Santiago       19603733.0
              Brazil             7  BRA      Brasilia      215313498.0
              Bolivia           80  BOL         Sucre       12224110.0
              Argentina         33  ARG  Buenos Aires       45510318.0

                              2020 Population  2015 Population  \
Continent     Country
Africa        Zimbabwe             15669666.0       14154937.0
              Zambia               18927715.0              NaN
              Western Sahara         556048.0         491824.0
              Uganda               44404611.0       37477356.0
              Tunisia              12161723.0       11557779.0
...                                       ...              ...
South America Colombia             50930662.0       47119728.0
              Chile                19300315.0       17870124.0
              Brazil              213196304.0      205188205.0
              Bolivia              11936162.0       11090085.0
              Argentina            45036032.0       43257065.0

                              2010 Population  2000 Population  \
Continent     Country
Africa        Zimbabwe             12839771.0       11834676.0
              Zambia               13792086.0        9891136.0
              Western Sahara         413296.0         270375.0
              Uganda               32341728.0       24020697.0
              Tunisia              10895063.0        9893316.0
...                                       ...              ...
South America Colombia                    NaN       39215135.0
              Chile                17004162.0       15351799.0
              Brazil              196353492.0      175873720.0
              Bolivia              10223270.0        8592656.0
              Argentina            41100123.0       37070774.0

                              1990 Population  1980 Population  \
Continent     Country
Africa        Zimbabwe             10113893.0        7049926.0
              Zambia                7686401.0        5720438.0
              Western Sahara         178529.0         116775.0
              Uganda               17586630.0       13284026.0
              Tunisia               8440023.0        6578156.0
...                                       ...              ...
South America Colombia             32601393.0       26176195.0
              Chile                13342868.0       11469828.0
              Brazil              150706446.0      122288383.0
              Bolivia               7096194.0        5736088.0
              Argentina            32637657.0       28024803.0

                              1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
Africa        Zimbabwe              5202918.0    390757.0            41.7665
              Zambia                4281671.0    752612.0            26.5976
              Western Sahara          76371.0    266000.0             2.1654
              Uganda               10317212.0    241550.0           195.6100
              Tunisia               5047404.0    163610.0            75.5218
...                                       ...         ...                ...
South America Colombia             20905254.0   1141748.0            45.4339
              Chile                 9820481.0    756102.0            25.9274
              Brazil               96369875.0   8515767.0            25.2841
              Bolivia               4585693.0   1098581.0            11.1272
              Argentina            23842803.0   2780400.0            16.3683

                              Growth Rate  World Population Percentage
Continent     Country
Africa        Zimbabwe             1.0204                         0.20
              Zambia               1.0280                         0.25
              Western Sahara       1.0184                         0.01
              Uganda               1.0304                         0.59
              Tunisia              1.0076                         0.15
...                                   ...                          ...
South America Colombia             1.0069                         0.65
              Chile                1.0057                         0.25
              Brazil               1.0046                         2.70
              Bolivia              1.0120                         0.15
              Argentina            1.0052                         0.57

[234 rows x 15 columns]

In [471]:
df4.swaplevel('Country', 'Continent') # it swap the index

,,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,Continent,,,,,,,,,,,,,,,
Zimbabwe,Africa,74,ZWE,Harare,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20
Zambia,Africa,63,ZMB,Lusaka,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Western Sahara,Africa,172,ESH,El Aaiún,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Uganda,Africa,31,UGA,Kampala,47249585.0,44404611.0,37477356.0,32341728.0,24020697.0,17586630.0,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
Tunisia,Africa,79,TUN,Tunis,12356117.0,12161723.0,11557779.0,10895063.0,9893316.0,8440023.0,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Colombia,South America,28,COL,Bogota,51874024.0,50930662.0,47119728.0,NaN,39215135.0,32601393.0,26176195.0,20905254.0,1141748.0,45.4339,1.0069,0.65
Chile,South America,65,CHL,Santiago,19603733.0,19300315.0,17870124.0,17004162.0,15351799.0,13342868.0,11469828.0,9820481.0,756102.0,25.9274,1.0057,0.25
Brazil,South America,7,BRA,Brasilia,215313498.0,213196304.0,205188205.0,196353492.0,175873720.0,150706446.0,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
Bolivia,South America,80,BOL,Sucre,12224110.0,11936162.0,11090085.0,10223270.0,8592656.0,7096194.0,5736088.0,4585693.0,1098581.0,11.1272,1.0120,0.15
Argentina,South America,33,ARG,Buenos Aires,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803.0,2780400.0,16.3683,1.0052,0.57

In [472]:
df.sort_index()
pd.set_option('display.max_rows', 230)

In [473]:

df.loc['Africa', 'Algeria'] # to access the data in the multple index we use the loc method

KeyError: 'Algeria'

In [ ]:
df.iloc[0]  # the iloc method is not efficient in the multiple index to access the right data that we want

index                                   0
Rank                                   36
CCA3                                  AFG
Capital                             Kabul
2022 Population                41128771.0
2020 Population                38972230.0
2015 Population                33753499.0
2010 Population                28189672.0
2000 Population                19542982.0
1990 Population                10694796.0
1980 Population                12486631.0
1970 Population                10752971.0
Area (km²)                       652230.0
Density (per km²)                 63.0587
Growth Rate                        1.0257
World Population Percentage          0.52
Name: (Asia, Afghanistan), dtype: object